### ISSUE TITLE
Extend example

### ISSUE THREAD

**Issue by RJuro** [yhatt/marp-cli-example#12]
Thanks for Marp and Marpit. One reason for me to use web-based slides is to be able to use media and interactive elements.

Could you perhaps add other more advanced elements to this example?
- video and video background?
- Perhaps even embedding of js? (e.g. https://github.com/ines/juniper)

Thanks

**Comment by yhatt** [comment]
This example is to show basic usage of Marp CLI for beginner. Surely your ideas are available in Marp, but there are out of Marp Markdown so you should use HTML.

But I and Marp team don't want to recommend positively to use HTML because of *potentially security risk*. Creating example showcase repository by community is suitable instead of this repository.

**Comment by RJuro** [comment]
Thanks a lot for the reply. I just wasn't sure if there was actually an option within Marp Markdown to do it without using HTML. That makes it clear :-)
