### ISSUE TITLE
Slide up and down like https://revealjs.com/#/2/2

### ISSUE THREAD

**Issue by ivakyb** [yhatt/marp-cli-example#7]
Yuki Hattori, Hello! Thank you for a super cool application. It works very good!!!

I have a question.
Is there a way to create slides like https://revealjs.com/#/2/2 ?

**Comment by yhatt** [comment]
No, there is not vertical slide in Marp because we think 2 way navigation is hard to notice for audience.

It may resolve to [make plugin for Marpit framework](https://marpit.marp.app/usage?id=extend-marpit-by-plugins), but it would be too hard. Probably continue using reveal.js is the best way if you still want navigation for 2 directions.
